const menu = [
    {
        id: 1,
        title: 'Bread & Cheese',
        category: 'Breakfast',
        price: 16.77,
        img: 'https://images.pexels.com/photos/103124/pexels-photo-103124.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    
    {
      id: 2,
        title: 'Noodle with soup',
        category: 'Lunch',
        price: 55.77,
        img: 'https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 3,
        title: 'Egg Cheese',
        category: 'Breakfast',
        price: 11.77,
        img: 'https://images.pexels.com/photos/101533/pexels-photo-101533.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 4,
        title: 'Orange Juice',
        category: 'Shakes',
        price: 22.72,
        img: 'https://images.pexels.com/photos/96974/pexels-photo-96974.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 5,
        title: 'Mixed fruits',
        category: 'Breakfast',
        price: 44.22,
        img: 'https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 6,
        title: 'Fried rice',
        category: 'Lunch',
        price: 66.22,
        img: 'https://images.pexels.com/photos/434258/pexels-photo-434258.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 7,
        title: 'Apple Juice',
        category: 'Shakes',
        price: 26.12,
        img: 'https://images.pexels.com/photos/616833/pexels-photo-616833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
{
        id: 8,
        title: 'Kellogs with milk',
        category: 'Breakfast',
        price: 36.32,
        img: 'https://images.pexels.com/photos/2115653/pexels-photo-2115653.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 9,
        title: 'Pasta',
        category: 'Lunch',
        price: 66.32,
        img: 'https://images.pexels.com/photos/1437267/pexels-photo-1437267.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
    {
        id: 10,
        title: 'Random Fruit juice',
        category: 'Shakes',
        price: 44.32,
        img: 'https://images.pexels.com/photos/1414131/pexels-photo-1414131.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2',
        desc: 'Biodiesel austin prism yr tousled thundercats occupy chillwave sustainable kinfolk DIY.',
    },
]

export default menu;